export const products = {

  "bar bender": [
    {
      id: 1,
      image: "/equipments/Bar_bender/GW20S.png",
      Model: "GW20S",
      Input_Voltage: "Single Phase / Three Phase Type 50-60 Hz",
      Diameter_Round_Bar: "04-20 mm",
      Diameter_Threaded_Steel: "04-18 mm",
      Diameter_of_WorkingDisc: "Q200mm",
      Adjustable_Bending_Speed: "25-30 Times / min",
      Working_Type: "Automatic/Manual/ CNC Digital",
      Motor_Power_Voltage: "2.2 kw/230V/220V ",
      Motor_RPM: "1440r/min",
      Pedals: "2 No",
      Dimensions: "800x550x800mm",
      Weight: "107KG",
    },
    {
      id: 2,
      Model: "GW20",
      image: "/equipments/Bar_bender/GW20.png",
      Input_Voltage: "Single Phase / Three Phase Type 50-60 Hz",
      Diameter_Round_Bar: "04-20 mm",
      Diameter_Threaded_Steel: "04-16 mm",
      Diameter_of_WorkingDisc: "Q200mm",
      Adjustable_Bending_Speed: "25-30 Times / min",
      Working_Type: "Automatic/Manual/CNC Digital",
      Motor_Power_Voltage: "3 kw/415V/380V",
      Motor_RPM: "1440r/min",
      Pedals: "2 No",
      Dimensions: "800x550x800mm",
      Weight: "107KG",
    },
    {
      id: 3,
      Model: "GW20D",
      image: "/equipments/Bar_bender/GW20D.png",
      Input_Voltage: "Single Phase / Three Phase Type 50-60 Hz",
      Diameter_Round_Bar: "04-20 mm",
      Diameter_Threaded_Steel: "04-16 mm",
      Diameter_of_WorkingDisc: "Q200mm",
      Adjustable_Bending_Speed: "25-30 Times / min",
      Working_Type: "Automatic/Manual/CNC Digital",
      Motor_Power_Voltage: "3 kw/220v/415V/380V",
      Motor_RPM: "1440r/min",
      Pedals: "2 No",
      Dimensions: "800x550x800mm",
      Weight: "117KG",
    },
    {
      id: 4,
      Model: "GF26",
      image: "/equipments/Bar_bender/GF26.png",
      Input_Voltage: "Single Phase / Three Phase Type 50-60 Hz",
      Diameter_Round_Bar: "04-22 mm",
      Diameter_Threaded_Steel: "04-26 mm",
      Diameter_of_WorkingDisc: "Q200mm",
      Adjustable_Bending_Speed: "25-30 Times / min",
      Working_Type: "Automatic/Manual/CNC Digital",
      Motor_Power_Voltage: "4 kw/380V/415V",
      Motor_RPM: "1440r/min",
      Pedals: "2 No",
      Dimensions: "900x600x1020mm",
      Weight: "180KG",
    },
    {
      id: 5,
      Model: "GWH32",
      image: "/equipments/Bar_bender/GWH32.png",
      Input_Voltage: "Three Phase 50-60 Hz",
      Diameter_Round_Bar: "16-32 mm",
      Diameter_Threaded_Steel: "16-32 mm",
      Diameter_of_WorkingDisc: "360mm",
      Adjustable_Bending_Speed: "10-20 R/min",
      Working_Type: "Automatic/Manual",
      Motor_Power_Voltage: "3.5 kw/415V/380V",
      Motor_RPM: "1440r/min",
      Pedals: "2 No",
      Dimensions: "850x850x1000mm",
      Weight: "320KG",
    },
    {
      id: 6,
      Model: "GWH36",
      image: "/equipments/Bar_bender/GWH36.png",
      Input_Voltage: "",
      Diameter_Round_Bar: "16-50 mm",
      Diameter_Threaded_Steel: "16-42 mm",
      Diameter_of_WorkingDisc: "360mm",
      Adjustable_Bending_Speed: "10-20 R/min",
      Working_Type: "Automatic/Manual",
      Motor_Power_Voltage: "5.5 kw/415V/380V",
      Motor_RPM: "1440r/min",
      Pedals: "2 No",
      Dimensions: "850x850x1000mm",
      Weight: "410KG",
    },
    {
      id: 7,
      Model: "GW40",
      image: "/equipments/Bar_bender/GW40.png",
      Input_Voltage: "380V/415V THREE PHASE 50-60 Hz",
      Diameter_Round_Bar: "6mm-40mm",
      Diameter_Threaded_Steel: "6mm-28mm",
      Diameter_of_WorkingDisc: "Ø 360mm",
      Adjustable_Bending_Speed: "10-20r/min",
      Working_Type: "Automatic/Manual",
      Motor_Power_Voltage: "3.2 kw",
      Motor_RPM: "1420RPM/MIN",
      Pedals: "1 PAD",
      Dimensions: "850X740X820 mm",
      Weight: "340 KGS",
    },
    {
      id: 8,
      Model: "GW42J",
      image: "/equipments/Bar_bender/GW42J.png",
      Input_Voltage: "380V/415V THREE PHASE 50-60 Hz",
      Diameter_Round_Bar: "6mm-40mm",
      Diameter_Threaded_Steel: "6mm-32mm",
      Diameter_of_WorkingDisc: "Ø 360mm",
      Adjustable_Bending_Speed: "10-20r/min",
      Working_Type: "Automatic/Manual",
      Motor_Power_Voltage: "3.5Kw",
      Motor_RPM: "1420RPM/MIN",
      Pedals: "1 PAD",
      Dimensions: "850X740X820 mm",
      Weight: "390 KGS",
    },
    {
      id: 9,
      Model: "GW42R",
      image: "/equipments/Bar_bender/GW42R.png",
      Input_Voltage: "380V/415V THREE PHASE 50-60 Hz",
      Diameter_Round_Bar: "6mm-40mm",
      Diameter_Threaded_Steel: "6mm-32mm",
      Diameter_of_WorkingDisc: "Ø 360mm",
      Adjustable_Bending_Speed: "10-20r/min",
      Working_Type: "Automatic/Manual",
      Motor_Power_Voltage: "3.75Kw",
      Motor_RPM: "1420RPM/MIN",
      Pedals: "1 PAD",
      Dimensions: "960x900x990mm",
      Weight: "420 KGS",
    },
    {
      id: 10,
      Model: "GW42D",
      image: "/equipments/Bar_bender/GW42D.png",
      Input_Voltage: "380V/415V THREE PHASE 50-60 Hz",
      Diameter_Round_Bar: "6mm-40mm",
      Diameter_Threaded_Steel: "6mm-32mm",
      Diameter_of_WorkingDisc: "Ø 360mm",
      Adjustable_Bending_Speed: "10-20r/min",
      Working_Type: "Automatic/CNC",
      Motor_Power_Voltage: "3.75Kw",
      Motor_RPM: "1420RPM/MIN",
      Pedals: "1 PAD",
      Dimensions: "850X740X820 mm",
      Weight: "400 KGS",
    },
    {
      id: 11,
      Model: "GW50",
      image: "/equipments/Bar_bender/GW50.png",
      Input_Voltage: "380V/415V THREE PHASE 50-60 Hz",
      Diameter_Round_Bar: "6mm-50mm",
      Diameter_Threaded_Steel: "6mm-42mm",
      Diameter_of_WorkingDisc: "Ø 360mm",
      Adjustable_Bending_Speed: "10-20r/min",
      Working_Type: "Automatic/Manual",
      Motor_Power_Voltage: "4.5Kw",
      Motor_RPM: "1420RPM/MIN",
      Pedals: "1 PAD",
      Dimensions: "1050X850X710mm",
      Weight: "470 KGS",
    },
  ],
  "bar cutter": [
    {
      id: 1,
      Model: "GQ40",
      image: "/equipments/bar_cutter/GQ40.png",
      Input_Voltage: "THREE PHASE 50-60 Hz",
      Diameter_Threaded_Steel: "Ø4mm-28mm",
      Diameter_Round_Bar: "Ø6mm-32mm",
      Cutting_Frequency: "32 Times/ Min",
      Working_Type: "Manual Push Type",
      Motor_Power_Voltage: "380V/415V",
      Motor_RPM: "2800 RPM 3.0kW",
      Dimensions: "1120X330X620MM",
      Weight: "380 KGS",
    },
    {
      id: 2,
      Model: "GQ42",
      image: "/equipments/bar_cutter/GQ42.png",
      Input_Voltage: "THREE PHASE 50-60 Hz",
      Diameter_Threaded_Steel: "Ø4mm-32mm",
      Diameter_Round_Bar: "Ø6mm-40mm",
      Cutting_Frequency: "32 Times/ Min",
      Working_Type: "Manual Push Type",
      Motor_Power_Voltage: "380V/415V",
      Motor_RPM: "2800 RPM 3.5kW",
      Dimensions: "1350X480X680 MM",
      Weight: "420 KGS",
    },
    {
      id: 3,
      Model: "GQ50",
      image: "/equipments/bar_cutter/GQ50.png",
      Input_Voltage: "THREE PHASE 50-60 Hz",
      Diameter_Threaded_Steel: "Ø4mm-42mm",
      Diameter_Round_Bar: "Ø6mm-50mm",
      Cutting_Frequency: "32 Times/ Min",
      Working_Type: "Manual Push Type",
      Motor_Power_Voltage: "380V/415V",
      Motor_RPM: "2800 RPM 4.2kW",
      Dimensions: "1400X550X850 MM",
      Weight: "510 KGS",
    },
  ],
  "portable bar bender": [
    {
      id: 1,
      Model: "RB16",
      image: "/equipments/portable_bar_bender/RB16.png",
      Voltage: "230V/110V/220V",
      Wattage: "800/900w",
      Working_Type: "Bender Only Hydraulic Type",
      Gross_Weight: "16.5 KGS",
      Machine_Weight: "15 KGS",
      Bending_Speed: "5 TIMES",
      Max_Bending_Dia: "Ø 16 MM",
      Min_Bending_Dia: null,
      Packing_Size: "670X250X245 MM",
      Machine_Size: "600X170X200 MM",
      Package_Type: "One Pcs/Carton/ Metal Box / Fiber Box",
      Certificate: "CE / ROHS",
    },
    {
      id: 2,
      Model: "RB25",
      image: "/equipments/portable_bar_bender/RB25.png",
      Voltage: "230V/110V/220V",
      Wattage: "950/1350w",
      Working_Type: "Bender Only Hydraulic Type",
      Gross_Weight: "32 KGS",
      Machine_Weight: "28 KGS",
      Bending_Speed: "5-8 TIMES",
      Max_Bending_Dia: "Ø 25 MM",
      Min_Bending_Dia: null,
      Packing_Size: "670X385X260MM",
      Machine_Size: "560X260X200 MM",
      Package_Type: "One Pcs/Carton/ Metal Box / Fiber Box",
      Certificate: "CE / ROHS",
    },
    {
      id: 3,
      Model: "RB32",
      image: "/equipments/portable_bar_bender/RB32.png",
      Voltage: "230V/110V/220V",
      Wattage: "1170w",
      Working_Type: "Bender Only Hydraulic Type",
      Gross_Weight: "36 KGS",
      Machine_Weight: "32 KGS",
      Bending_Speed: "8-10 TIMES",
      Max_Bending_Dia: "Ø 32MM",
      Min_Bending_Dia: "Ø 4MM",
      Packing_Size: "760X385X260MM",
      Machine_Size: "560X260X200MM",
      Package_Type: "One Pcs/Carton/ Metal Box / Fiber Box",
      Certificate: "CE / ROHS",
    },
    {
      id: 4,
      Model: "HRB32",
      image: "/equipments/portable_bar_bender/HRB32.png",
      Voltage: "230V/110V/220V",
      Wattage: "1200w",
      Working_Type: "Bender / Straightner\nHydraulic Type",
      Gross_Weight: "36KGS",
      Machine_Weight: "32 KGS",
      Bending_Speed: "8-10 TIMES",
      Max_Bending_Dia: "Ø 32MM",
      Min_Bending_Dia: null,
      Packing_Size: "760X385X260MM",
      Machine_Size: "560X260X200MM",
      Package_Type: "One Pcs/Carton/ Metal Box / Fiber Box",
      Certificate: "CE / ROHS",
    },
  ],
  "portable bar cutter": [
    {
      id: 1,
      Model: "RC16",
      Voltage: "220V / 110V",
      Wattage: "850/900w",
      Working_Type: "Cutter Only Hydraulic Type",
      Gross_Weight: "16.5 KGS",
      Machine_Weight: "15 KGS",
      Cutting_Speed: "5-8 TIMES",
      Max_Cutting_Dia: "Ø 16 MM",
      Min_Cutting_Dia: "Ø 4 MM",
      Packing_Size: "670X250X245 MM",
      Machine_Size: "600X170X200 MM",
      Package_Type: "One Pcs/Carton/ Metal Box / Fiber Box",
      Certificate: "CE / ROHS",
    },
    {
      id: 2,
      Model: "RC20",
      Voltage: "220V / 110V",
      Wattage: "1400/1600w",
      Working_Type: "Cutter Only Hydraulic Type",
      Gross_Weight: "18 KGS",
      Machine_Weight: "16 KGS",
      Cutting_Speed: "5-8 TIMES",
      Max_Cutting_Dia: "Ø 20 MM",
      Min_Cutting_Dia: "Ø 4 MM",
      Packing_Size: "670X385X260MM",
      Machine_Size: "560X260X200 MM",
      Package_Type: "One Pcs/Carton/ Metal Box / Fiber Box",
      Certificate: "CE / ROHS",
    },
    {
      id: 3,
      Model: "RC25",
      Voltage: "220V/110V",
      Wattage: "1600/1700w",
      Working_Type: "Cutter Only Hydraulic Type",
      Gross_Weight: "22 KGS",
      Machine_Weight: "19 KGS",
      Cutting_Speed: "5-8 TIMES",
      Max_Cutting_Dia: "Ø 25 MM",
      Min_Cutting_Dia: "Ø 4 MM",
      Packing_Size: "670X385X260MM",
      Machine_Size: "560X260X200 MM",
      Package_Type: "One Pcs/Carton/ Metal Box / Fiber Box",
      Certificate: "CE / ROHS",
    },
    {
      id: 4,
      Model: "RB32",
      Voltage: "220V/110V",
      Wattage: "2900/3000w",
      Working_Type: "Cutter Only Hydraulic Type",
      Gross_Weight: "36 KGS",
      Machine_Weight: "32 KGS",
      Cutting_Speed: "8-10 TIMES",
      Max_Cutting_Dia: "Ø 32MM",
      Min_Cutting_Dia: "Ø 4 MM",
      Packing_Size: "760X385X260MM",
      Machine_Size: "560X260X200MM",
      Package_Type: "One Pcs/Carton/ Metal Box / Fiber Box",
      Certificate: "CE / ROHS",
    },
  ],
  "portable machine": [
    {
      id: 1,
      Model: "NRT-25",
      Battery: "DC 14 4V 4.0Ah",
      DiaSize: "25mm",
      Gross_Weight: "7.65 KGS",
      Machine_Weight: "3.5 KGS",
      Turns_Per_Tie: "2/3 TURNS",
      Length_Per_Tie: "430MM/2 WRAPS",
      Ties_Per_Coil: "230 TIES/2 TURNS",
      Diameter_Of_Wire: "0.8MM",
      Carton_Size: "515X415X150MM",
      Machine_Size: "285X296X100MM",
      Certificate: "CE / ROHS",
      Accessories: "2 PCS BATTERY, CHARGER, 4 SET COIL, CARRY CASE",
    },
    {
      id: 2,
      Model: "NRT-40",
      Battery: "DC 14 4V 4.0Ah",
      DiaSize: "40mm",
      Gross_Weight: "8 KGS",
      Machine_Weight: "4.5 KGS",
      Turns_Per_Tie: "2/3 TURNS",
      Length_Per_Tie: "600MM/2 WRAPS",
      Ties_Per_Coil: "160 TIES/2 TURNS",
      Diameter_Of_Wire: "0.8MM",
      Carton_Size: "515X415X150MM",
      Machine_Size: "285X296X100MM",
      Certificate: "CE / ROHS",
      Accessories: "2 PCS BATTERY, CHARGER, 4 SET COIL, CARRY CASE",
    },
    {
      id: 3,
      Model: "RCT36",
      WrenchSize: "16-36MM",
      Power: "2800KW",
      Voltage: "220V-230V",
      Weight: "15Kgs",
      Speed: "60RPM",
    },
    {
      id: 4,
      Model: "RCT42",
      WrenchSize: "16-42MM",
      Power: "3200KW",
      Voltage: "220V-230V",
      Weight: "20Kgs",
      Speed: "60RPM",
    },
    {
      id: 5,
      Model: "RFC-40",
      Voltage: "220V/110V",
      Wattage: "900W",
      Type: "Electric Armature Type",
      Gross_Weight: "7KGS",
      Machine_Weight: "4KGS",
      Cutting_Speed: "100/MIN",
      Max_Cutting_Dia: "42MM",
      Min_Cutting_Dia: "4MM",
      Packing_Size: "42x17x11CM",
      Machine_Size: "42x11CM",
      Package_Type: "CartonBOX",
      Certificate: "CE/ROHS",
    },
  ],
  "bar threading machine": [
    {
      id: 1,
      Model: "CDRG-45R",
      Threading_Diameter: "16-45 mm",
      Thread_Pitch_Helix_Angle: "2.5/3.0/3.5 (123 TYPE)",
      Working_Type: "Sensor Type",
      Thread_Angle: "75/60 Degree",
      Speed: "62-80 RPM/MIN",
      Motor_Power: "5.5 KW/380 V/415V",
      Threading_Length: "100 mm",
      Dimensions: "1300*600*1200mm",
      Weight: "380 Kgs",
      Gross_Weight: "430 Kgs",
      Motor_Type: "Three Phase 50-60Hz",
    },
    {
      id: 2,
      Model: "CDRG-40R",
      Threading_Diameter: "16-40 mm",
      Thread_Pitch_Helix_Angle: "2.5/3.0/3.5 (123 TYPE)",
      Working_Type: "Limit Switch Type",
      Thread_Angle: "75/60 Degree",
      Speed: "62-80 RPM/MIN",
      Motor_Power: "5.5 KW/380 V/415V",
      Threading_Length: "100 mm",
      Dimensions: "1300*600*1200mm",
      Weight: "380 Kgs",
      Gross_Weight: "430 Kgs",
      Motor_Type: "Three Phase 50-60Hz",
    },
    {
      id: 3,
      Model: "HGS40R",
      Threading_Diameter: "06-40 mm",
      Thread_Pitch_Helix_Angle: "2.0/2.5/3.0/3.5 (0.0.0 TYPE)",
      Working_Type: "Sensor/Limit Switch Type",
      Thread_Angle: "60 Degree",
      Speed: "62-80 RPM/MIN",
      Motor_Power: "4.2 KW/380 V/415V",
      Threading_Length: "80 mm",
      dimensions: "1520*830*1200mm",
      weight: "310 Kgs",
      Gross_Weight: "390 Kgs",
      Motor_Type: "Three Phase 50-60Hz",
    },
    {
      id: 4,
      Model: "HGS50R",
      Threading_Diameter: "06-50 mm",
      Thread_Pitch_Helix_Angle: "2.0/2.5/3.0/3.5/4.0 (0.0.0 TYPE)",
      Working_Type: "Sensor/Limit Switch Type",
      Thread_Angle: "60 Degree",
      Speed: "62-80 RPM/MIN",
      Motor_Power: "7.5 KW/380 V/415V",
      Threading_Length: "150 mm",
      dimensions: "1520*830*1200mm",
      weight: "420 Kgs",
      Gross_Weight: "450 Kgs",
      Motor_Type: "Three Phase 50-60Hz",
    },
  ],
  "scraper straightening machine": [
    {
      id: 1,
      Model: "RGX14",
      straightening_Diameter: "6-14mm",
      working_Speed: "28MTR/MIN",
      straightening_Length: "500-3000MM",
      straightener_Motor_Power: "5.5Kw",
      cutting_Motor_Power: "2.2Kw",
      voltage_Phase: "380V/415V (Three Phase) 50-60Hz",
      cutting_Thickness: "6-14 mm",
      packing_Size: "1180*700*1280mm",
      weight: "720KGS",
    },
    {
      id: 2,
      Model: "RGX25",
      straightening_Diameter: "16-25mm",
      working_Speed: "28MTR/MIN",
      straightening_Length: "500-3000MM",
      straightener_Motor_Power: "15Kw",
      cutting_Motor_Power: "2.2Kw",
      voltage_Phase: "380V/415V (Three Phase) 50-60Hz",
      cutting_Thickness: "16- 25mm",
      packing_Size: "1380*7870*1400mm",
      weight: "1000KGS",
    },
  ],
  "decoil machine": [
    {
      id: 1,
      Model: "GT4-14A",
      name: "Hydraulic steel bar straightening machine",
      weight: "650KG",
      straighten_Rebar_Diameter: "4-12mm",
      straighten_The_Diameter_Of_Round_Steel: "4-14mm",
      Motor_Power: "11KW 5.5KW",
      straightening_Frame_Size: "800mm",
      dimension_Of_Straightening_Wheel: "54*70mm",
      belt_Rack: "8m",
      motor_Speed: "1440R/min",
      cutting_Error: "No error",
      straightening_Speed: "0-85m adjustable",
      size: "2000*700*200mm",
    },
    {
      id: 2,
      Model: "GT4-14B",
      name: "Hydraulic steel bar straightening machine",
      weight: "550KG",
      straighten_Rebar_Diameter: "5-10mm",
      straighten_The_Diameter_Of_Round_Steel: "5-12mm",
      Motor_Power: "9KW",
      straightening_Frame_Size: "800mm",
      dimension_Of_Straightening_Wheel: "54*70mm",
      belt_Rack: "8m",
      motor_Speed: "1440R/min",
      cutting_Error: "<1cm",
      straightening_Speed: "40M/ min",
      size: "2000*750*1000mm",
    },
    {
      id: 3,
      Model: "GT4-14C",
      straightening_Range_Round_Bar: "5-14mm",
      straightening_Range_DeformedBar: "5-12mm",
      straightening_Wheels: "8 PCS",
      Cutting_Speed: "45m/min",
      voltage: "THREE PHASE: 380VAC/415VAC OR CUSTOMIZED",
      Motor_Power: "5.5 KW + 9 KW",
      overall_Size: "2450x750x1000mm",
      weight: "800KGS",
    },
    {
      id: 4,
      Model: "GT4-14D",
      straightening_Range_Round_Bar: "5-14mm",
      straightening_Range_DeformedBar: "5-12mm",
      straightening_Wheels: "8 PCS",
      Cutting_Speed: "60m/min",
      voltage: "THREE PHASE: 380VAC/415VAC OR CUSTOMIZED",
      Motor_Power: "5.5 KW + 15 KW",
      overall_Size: "2850x750x1000mm",
      weight: "1000KGS",
    },
    {
      id: 5,
      Model: "GT4-14E",
      straightening_Range_Round_Bar: "5-14mm",
      straightening_Range_DeformedBar: "5-12mm",
      straightening_Wheels: "8 PCS",
      Cutting_Speed: "0-80m/min",
      voltage: "THREE PHASE: 380VAC/415VAC OR CUSTOMIZED",
      Motor_Power: "5.5 KW + 15 KW",
      overall_Size: "3000x750x1000mm",
      weight: "1200KGS",
    },
    {
      id: 6,
      Model: "GT4-10",
      Motor_Power: "7.5kW (1440r/min)",
      straighten_Rebar_Diameter: "≤10mm",
      straighten_The_Diameter_Of_Round_Steel: "≤12mm",
      straightening_Speed: "25-35m/min",
      cutting_Error: "≤1cm",
      oilPump: "16 gear pump",
      Input_Voltage: "3 phase 380V",
      size: "1440×500×900mm",
      weight: "260KGS",
    },
    {
      id: 7,
      Model: "GT4-12",
      Motor_Power: "9kW (1440r/min)",
      straighten_Rebar_Diameter: "≤12mm",
      straighten_The_Diameter_Of_Round_Steel: "≤12mm",
      straightening_Speed: "25-35m/min",
      cutting_Error: "≤1cm",
      oilPump: "25 gear pump",
      Input_Voltage: "3 phase 380V",
      size: "1700×550×1000mm",
      weight: "330KGS",
    },
    {
      id: 8,
      Model: "GTW4-10",
      capacity_For_Single_Line: "4-10mm",
      capacity_For_Double_Line: "4-8mm",
      max_Bending_Angle: "+180°",
      bending_Direction: "Clockwise",
      Motor_Power_For_Feeding: "9.5KW",
      Motor_Power_For_Bending: "3.75KW",
      weight: "1900KGS",
      dimension: "3650×1100×1900mm",
    },
    {
      id: 9,
      Model: "GTW4-12",
      capacity_For_Single_Line: "4-12mm",
      capacity_For_Double_Line: "4-10mm",
      maxBending_Angle: "+180°",
      bending_Direction: "Clockwise",
      Motor_Power_For_Feeding: "15KW",
      Motor_Power_For_Bending: "5.5KW",
      weight: "2200KGS",
      dimension: "4100×1220×2040mm",
    },
  ],
  "punching shearing machine": [
    {
      id: 1,
      Model: "QA32-8",
      Max_Shearing_Force: "400KN",
      Cutter_Stoke_Length: "27mm",
      Cutting_Frequency: "30 times/min",
      Motor_Power: "2.2KW,380V,50Hz (3HP)",
      Size: "1000*500*1170mm",
      Weight: "500Kg",
      Shearing_Thickness: "08 mm",
      Angle_Steel: "80x80x08",
      Channel_Steel: "GB 100#",
      Round_Hole: "Dia.22x8mm",
      Long_Hole: "40x17x8mm",
      Cutting_Board: "200x12mm",
      Round_Bar: "Dia.30mm",
      Square_Steel: "20x20mm",
      Flat_Steel: "75x75mm",
      VAngle: "50x50",
      Bevel: "70x70",
    },
    {
      id: 2,
      Model: "QA32-10",
      Max_Shearing_Force: "600KN",
      Cutter_Stoke_Length: "30mm",
      Cutting_Frequency: "30 times/min",
      Motor_Power: "3 KW,380V, 50Hz (4 HP)",
      Size: "1100*700*1600mm",
      Weight: "750Kg",
      Shearing_Thickness: "10mm",
      Angle_Steel: "100×100×10",
      Channel_Steel: "GB 120#",
      Round_Hole: "Dia.25x10mm",
      Long_Hole: "40x18x10mm",
      Cutting_Board: "240×10mm",
      Round_Bar: "Dia.35mm",
      Square_Steel: "20x20mm",
      Flat_Steel: "75×75mm",
      VAngle: "50×50",
      Bevel: "100×100",
    },
    {
      id: 3,
      Model: "QA32-12",
      Max_Shearing_Force: "900KN",
      Cutter_Stoke_Length: "36mm",
      Cutting_Frequency: "30 times/min",
      Motor_Power: "4KW, 380V, 50Hz (5.5HP)",
      Size: "1100*800*1500mm",
      Weight: "1100 Kg",
      Shearing_Thickness: "12mm",
      Angle_Steel: "125x125x12",
      Channel_Steel: "GB 140#",
      Round_Hole: "Dia.31x12mm",
      Long_Hole: "40x21x12mm",
      Cutting_Board: "330x20mm",
      Round_Bar: "Dia.40mm",
      Square_Steel: "35×35mm",
      Flat_Steel: "75×75mm",
      VAngle: "50x50",
      Bevel: "125x125",
    },
    {
      id: 4,
      Model: "QA32-14",
      Max_Shearing_Force: "1000KN",
      Cutter_Stoke_Length: "36 mm",
      Cutting_Frequency: "30 times/min",
      Motor_Power: "4KW, 380V, 50Hz (5.5HP)",
      Size: "1200*800*1500mm",
      Weight: "1300 Kg",
      Shearing_Thickness: "12mm",
      Angle_Steel: "135x135x12",
      Channel_Steel: "GB 160#",
      Round_Hole: "Dia31x14mm",
      Long_Hole: "40x21x14mm",
      Cutting_Board: "330x22mm",
      Round_Bar: "Dia.40mm",
      Square_Steel: "35×35mm",
      Flat_Steel: "75×75mm",
      VAngle: "50x50",
      Bevel: "125x125",
    },
  ],
  "power trowels/ power floater": [
    {
      id: 1,
      Model: "PL16",
      Drive_Type: "Motor 1PH 220V",
      Disc_Size: "380mm Diameter",
      Blades: "NA",
      PanQty: "1 Nos",
      Speed: "280-2800 RPM",
      PowerHP: "1680W",
      Dimensions: "380x340x320 mm",
      Weight: "7 Kgs",
    },
    {
      id: 2,
      Model: "RWT24",
      Drive_Type: "Engine",
      Disc_Size: "600mm Diameter",
      Blades: "4 Nos",
      PanQty: "1 Nos",
      Speed: "3600 RPM",
      PowerHP: "5.5 hp",
      Dimensions: "600X300X600 mm",
      Weight: "60 Kgs",
    },
    {
      id: 3,
      Model: "RWT38",
      Drive_Type: "Motor / Engine",
      Disc_Size: "880mm Diameter",
      Blades: "4 Nos",
      PanQty: "1 Nos",
      Speed: "3600 RPM",
      PowerHP: "5.5 hp",
      Dimensions: "1820x945x 880 mm",
      Weight: "84 Kgs",
    },
    {
      id: 4,
      Model: "RWT40",
      Drive_Type: "Motor / Engine",
      Disc_Size: "980mm Diameter",
      Blades: "4 Nos",
      PanQty: "1 Nos",
      Speed: "3600 RPM",
      PowerHP: "5.5 hp",
      Dimensions: "1820x945x 980 mm",
      Weight: "90 Kgs",
    },
    {
      id: 5,
      Model: "RWT48",
      Drive_Type: "Motor / Engine",
      Disc_Size: "1000mm Diameter",
      Blades: "4 Nos",
      PanQty: "1 Nos",
      Speed: "3600 RPM",
      PowerHP: "5.5 hp",
      Dimensions: "1820x945x1000 mm",
      Weight: "102 Kgs",
    },
    {
      id: 6,
      Model: "RWT52",
      Drive_Type: "Motor/Engine",
      Disc_Size: "1000mm Diameter",
      Blades: "4 Nos",
      PanQty: "1 Nos",
      Speed: "3600 RPM",
      PowerHP: "5.5 hp",
      Dimensions: "1820x945x1000 mm",
      Weight: "128 Kgs",
    },
  ],
  "ride on trowel": [
    {
      id: 1,
      Model: "RT28",
      Drive: "Petrol Honda GX390",
      Speed: "90-140 RPM",
      Blades: "4-4",
      Blade_Size: "350 x 150 x 2 mm",
      Disk_Size: "900mm Diameter",
      Work_Length: "1800x900 mm",
      Efficiency: "800 Square meter per hour",
      Engine_Power: "13 HP (3600 RPM)",
      Dimensions: "1900 x920x 880 mm",
      Weight: "380 Kgs",
    },
    {
      id: 2,
      Model: "RT36",
      Drive: "Petrol Honda GX690",
      Speed: "90-140 RPM",
      Blades: "4-4",
      Blade_Size: "350 x 150 x 2 mm",
      Disk_Size: "1000mm Diameter",
      Work_Length: "2000x1000 mm",
      Efficiency: "800 Square meter per hour",
      Engine_Power: "24 HP (3600 RPM)",
      Dimensions: "2100 x1100x 1180 mm",
      Weight: "530 Kgs",
    },
    {
      id: 3,
      Model: "RT36L",
      Drive: "Petrol Honda GX690",
      Speed: "90-140 RPM",
      Blades: "4-4",
      Blade_Size: "350 x 150 x 2 mm",
      Disk_Size: "1000mm Diameter",
      Work_Length: "2000x1000 mm",
      Efficiency: "800 Square meter per hour",
      Engine_Power: "24 HP (3600 RPM)",
      Dimensions: "2100 x1100x 1180 mm",
      Weight: "480 Kgs",
    },
  ],
  "concrete cutter / groove cutter": [
    {
      id: 1,
      Model: "RCS10",
      CuttingWidth: "2-4 mm",
      MaxCuttingDepth: "105mm",
      DrivingMethod: "Hand Type",
      DepthAdjustment: "Manual",
      Blade_Size: "350mm",
      MaximumRPM: "4300RPM",
      WaterTankCapacity: "NA",
      Drive: "Electric 1 Phase Motor",
      HorsePowerVariant: "3600W (Load Power: 5200W)",
      Dimension: "305*3*25.4mm",
      WeightOnlyFrameBody: "9 KGS",
    },
    {
      id: 2,
      Model: "RCS14",
      CuttingWidth: "5-8 mm",
      MaxCuttingDepth: "150mm",
      DrivingMethod: "Manual / Walk Behind Push Type",
      DepthAdjustment: "Manual Handle Rotation With Hydraulic Jack Type",
      Blade_Size: "400-500mm",
      MaximumRPM: "1440 RPM-3600 RPM",
      WaterTankCapacity: "25LTR",
      Drive: "Single Phase Motor/ Three Phase Motor / Petrol / Diesel Engine",
      HorsePowerVariant:
        "(Electric Motor 5Hp-25Hp) | (Petrol Engine 5-24HP) | (Diesel Engine 5HP-20Hp)",
      Dimension: "930x565x1020",
      WeightOnlyFrameBody: "75 KGS",
    },
    {
      id: 3,
      Model: "RCS16",
      CuttingWidth: "5-8 mm",
      MaxCuttingDepth: "180mm",
      DrivingMethod: "Manual / Walk Behind Push Type",
      DepthAdjustment: "Manual Handle Rotation With Hydraulic Jack Type",
      Blade_Size: "400-500mm",
      MaximumRPM: "1440 RPM-3600 RPM",
      WaterTankCapacity: "35 Liters",
      Drive: "Single Phase Motor/ Three Phase Motor / Petrol / Diesel Engine",
      HorsePowerVariant:
        "(Electric Motor 5Hp-25Hp) | (Petrol Engine 5-24HP) | (Diesel Engine 5HP-20Hp)",
      Dimension: "1000*540*840",
      WeightOnlyFrameBody: "80 KGS",
    },
    {
      id: 4,
      Model: "RCS18",
      CuttingWidth: "5-8 mm",
      MaxCuttingDepth: "180mm",
      DrivingMethod: "Manual / Walk Behind Push Type",
      DepthAdjustment: "Manual Handle Rotation With Hydraulic Jack Type",
      Blade_Size: "400-500mm",
      MaximumRPM: "1440 RPM-3600 RPM",
      WaterTankCapacity: "35 Liters",
      Drive: "Single Phase Motor/ Three Phase Motor / Petrol / Diesel Engine",
      HorsePowerVariant:
        "(Electric Motor 5Hp-25Hp) | (Petrol Engine 5-24HP) | (Diesel Engine 5HP-20Hp)",
      Dimension: "1000*540*840",
      WeightOnlyFrameBody: "95 KGS",
    },
    {
      id: 5,
      Model: "RCS18H",
      CuttingWidth: "5-8 mm",
      MaxCuttingDepth: "180mm",
      DrivingMethod: "Gear Rotate / Walk Behind Push",
      DepthAdjustment: "Manual Handle Rotation With Hydraulic Jack Type",
      Blade_Size: "400-500mm",
      MaximumRPM: "1440 RPM-3600 RPM",
      WaterTankCapacity: "35 Liters",
      Drive: "Single Phase Motor/ Three Phase Motor / Petrol / Diesel Engine",
      HorsePowerVariant:
        "(Electric Motor 5Hp-25Hp) | (Petrol Engine 5-24HP) | (Diesel Engine 5HP-20Hp)",
      Dimension: "1000*540*840",
      WeightOnlyFrameBody: "110 KGS",
    },
    {
      id: 6,
      Model: "RCS19",
      CuttingWidth: "5-8 mm",
      MaxCuttingDepth: "180mm",
      DrivingMethod: "Manual / Walk Behind Push Type",
      DepthAdjustment: "Manual Handle Rotation With Hydraulic Jack Type",
      Blade_Size: "400-500mm",
      MaximumRPM: "1440 RPM-3600 RPM",
      WaterTankCapacity: "35 Liters",
      Drive: "Single Phase Motor/ Three Phase Motor / Petrol / Diesel Engine",
      HorsePowerVariant:
        "(Electric Motor 5Hp-25Hp) | (Petrol Engine 5-24HP) | (Diesel Engine 5HP-20Hp)",
      Dimension: "1000*540*840",
      WeightOnlyFrameBody: "100 KGS",
    },
    {
      id: 7,
      Model: "RCS20",
      CuttingWidthmm: "5-8 mm",
      MaxCuttingDepthmm: "180mm",
      DrivingMethod: "Manual / Walk Behind Push Type",
      DepthAdjustment: "Manual Handle Rotation With Hydraulic Jack Type",
      Blade_Sizemm: "400-500mm",
      MaximumRPM: "1440 RPM-3600 RPM",
      WaterTankCapacity: "35 Liters",
      Drive: "Single Phase Motor/ Three Phase Motor / Petrol / Diesel Engine",
      HorsePowerVariant:
        "(Electric Motor 5Hp-25Hp) I (Petrol Engine 5-24HP) I (Diesel Engine 5HP-20Hp)",
      Dimension: "1000x500x950",
      WeightOnlyFrameBody: "100 KGS",
    },
    {
      id: 8,
      Model: "RCS20A",
      CuttingWidthmm: "5-10mm",
      MaxCuttingDepthmm: "180mm",
      DrivingMethod: "Manual / Walk Behind Push Type",
      DepthAdjustment: "Manual Handle Rotation With Hydraulic Jack Type",
      Blade_Sizemm: "400-500mm",
      MaximumRPM: "1440 RPM-3600 RPM",
      WaterTankCapacity: "35 Liters",
      Drive: "Single Phase Motor/ Three Phase Motor / Petrol / Diesel Engine",
      HorsePowerVariant:
        "(Electric Motor 5Hp-25Hp) I (Petrol Engine 5-24HP) I (Diesel Engine 5HP-20Hp)",
      Dimension: "1000x600x950",
      WeightOnlyFrameBody: "110 KGS",
    },
    {
      id: 9,
      Model: "RCS22",
      CuttingWidthmm: "5-10mm",
      MaxCuttingDepthmm: "220mm",
      DrivingMethod: "Manual / Walk Behind Push Type",
      DepthAdjustment: "Manual Handle Rotation With Hydraulic Jack Type",
      Blade_Sizemm: "600mm",
      MaximumRPM: "1440 RPM-3600 RPM",
      WaterTankCapacity: "35 Liters",
      Drive: "Single Phase Motor/ Three Phase Motor / Petrol / Diesel Engine",
      HorsePowerVariant:
        "(Electric Motor 5Hp-25Hp) I (Petrol Engine 5-24HP) I (Diesel Engine 5HP-20Hp)",
      Dimension: "1100*600*1000",
      WeightOnlyFrameBody: "145 KGS",
    },
    {
      id: 10,
      Model: "RCS28",
      CuttingWidthmm: "5-10mm",
      MaxCuttingDepthmm: "260mm",
      DrivingMethod: "Manual / Walk Behind Push Type",
      DepthAdjustment: "Manual Handle Rotation With Hydraulic Jack Type",
      Blade_Sizemm: "700mm",
      MaximumRPM: "1440 RPM-3600 RPM",
      WaterTankCapacity: "40 LTR",
      Drive: "Single Phase Motor/ Three Phase Motor / Petrol / Diesel Engine",
      HorsePowerVariant:
        "(Electric Motor 5Hp-25Hp) I (Petrol Engine 5-24HP) I (Diesel Engine 5HP-20Hp)",
      Dimension: "1400x700x1150",
      WeightOnlyFrameBody: "130 KGS",
    },
    {
      id: 11,
      Model: "RCS40",
      CuttingWidthmm: "5-14mm",
      MaxCuttingDepthmm: "400mm",
      DrivingMethod: "Manual / Walk Behind Push Type",
      DepthAdjustment: "Manual Handle Rotation With Hydraulic Jack Type",
      Blade_Sizemm: "1000mm",
      MaximumRPM: "1440 RPM-3600 RPM",
      WaterTankCapacity: "50 Ltr",
      Drive: "Single Phase Motor/ Three Phase Motor / Petrol / Diesel Engine",
      HorsePowerVariant:
        "(Electric Motor 5Hp-25Hp) I (Petrol Engine 5-24HP) I (Diesel Engine 5HP-20Hp)",
      Dimension: "1700x750x1250",
      WeightOnlyFrameBody: "180 KGS",
    },
  ],
  "vibrator screed": [
    {
      id: 1,
      Model: "RVS25R",
      Blade_Size: "1-6 Mtr",
      Drive: "Robin Engine",
      DriveSystem: "Flexible shaft AirCooled 4 Stroke Engine",
      MaxOutputkw: "1.2 kw",
      Maxspeedrpm: "5200 RPM",
      Dimensions: "LxW400xH390",
      Weight: "30 KGS",
    },
    {
      id: 2,
      Model: "RVS25H",
      Blade_Size: "1-6 Mtr",
      Drive: "Honda Engine",
      DriveSystem: "Flexible shaft AirCooled 4 Stroke Engine",
      MaxOutputkw: "1.4 kw",
      Maxspeedrpm: "5200 RPM",
      Dimensions: "LxW400xH390",
      Weight: "32 KGS",
    },
    {
      id: 3,
      Model: "RVS25E",
      Blade_Size: "1-6 Mtr",
      Drive: "3Phase Motor",
      DriveSystem: "Vibrate motor",
      MaxOutputkw: "NA",
      Maxspeedrpm: "2800 RPM",
      Dimensions: "LxW190xH131",
      Weight: "25 KGS",
    },
    {
      id: 4,
      Model: "RVS25ES",
      Blade_Size: "1-6 Mtr",
      Drive: "1Phase Motor",
      DriveSystem: "Vibrate motor",
      MaxOutputkw: "0.15kw",
      Maxspeedrpm: "2800 RPM",
      Dimensions: "LxW190xH131",
      Weight: "25 KGS",
    },
    {
      id: 5,
      Model: "RVS10B",
      ProductName: "Lithium battery leveling ruler",
      RotatingSpeed: "3000-6000r/min",
      Voltage: "48V",
      Power: "Brushed motor",
      ScraperLength: "1.5M",
      BatteryCapacity: "6000mA",
      DrivingSpeed: "10m/min",
      TotalWeight: "5kg",
    },
  ],
  "concrete vibratory paver": [
    {
      id: 1,
      Model: "RVP219-4",
      LengthoftheRoller: "4000mm",
      VibratoryFrequency: "50-60Hz",
      VibrationForce: "4.5-5.5KN",
      PavingThickness: "300mm",
      SpreadThickness: "250-300mm",
      VibratorsNeedle: "8NoS",
      QtyRoller_Auger: "2 Rollers & 1 Auger",
      WalkingSpeed: "5-7 Mtr/min",
      Max_TotalPower: "25.7 Kw",
      VibrationMotor_Power: "2.2 kwPerSet",
      LiftingMotor: "2.2-3.0 kw",
      TravellingMotor: "4 kw",
      AugerMotor: "4 kw",
      WorkingWidth: "3.8MTR",
      Voltage_Phase: "380V/415V 3Phase",
      Dimensions: "5500x1200x980mm",
      Weight: "1200Kg",
    },
    {
      id: 2,
      Model: "RVP219-6",
      LengthoftheRoller: "6000mm",
      VibratoryFrequency: "50-60Hz",
      VibrationForce: "4.5-5.5 KN",
      PavingThickness: "300 mm",
      SpreadThickness: "250-300 mm",
      VibratorsNeedle: "10 NoS",
      QtyRoller_Auger: "2 Rollers & 1 Auger",
      WalkingSpeed: "5-7 Mtr/min",
      Max_TotalPower: "25.7Kw",
      VibrationMotor_Power: "2.2kwPerSet",
      LiftingMotor: "2.2-3.0kw",
      TravellingMotor: "5.5kw",
      AugerMotor: "5.5kw",
      WorkingWidth: "5.8MTR",
      Voltage_Phase: "380V/415V3Phase",
      Dimensions: "5500x1200x980mm",
      Weight: "1350Kg",
    },
  ],
  "truss screed": [
    {
      id: 1,
      Model: "RTS600S",
      Body: "Metal Frame",
      Drive: "Motor/Engine",
      Power: "5.5HP-13 HP",
      MaxRotateSpeed: "3600 RPM",
      ScreedLength: "4-18 Mtr",
      TravelSpeed: "8-10m/min",
      FrameType: "Multi Joints",
      DegreeAdjustments: "5°-10°",
      MaxPavingThickness: "260mm",
      Dimensions: "Lx400x960 mm",
    },
    {
      id: 2,
      Model: "RTS600A",
      Body: "Aluminium Frame",
      Drive: "Motor/Engine",
      Power: "5.5HP-13 HP",
      MaxRotateSpeed: "3600 RPM",
      ScreedLength: "4-18 Mtr",
      TravelSpeed: "8-10m/min",
      FrameType: "Multi Joints",
      DegreeAdjustments: "5°-10°",
      MaxPavingThickness: "260mm",
      Dimensions: "Lx400x960 mm",
    },
  ],
  "plate compactor": [
    {
      id: 1,
      Model: "RPC200E",
      Drive_Type: "Electric Motor",
      Powerkwhp: "4.0kw/5.5hp\n(3P/1P/415V)",
      CentrifugalForce: "30kn",
      CompactionDepth: "30cm",
      TravelSpeed: "6-16m/min",
      MovementType: "Reverse/Forward",
      CompactionPlateSize: "500 x 650 x 12 mm",
      RPM: "2800rpm",
      Weight: "150Kg",
    },
    {
      id: 2,
      Model: "RPC160",
      Drive_Type: "Diesel / Petrol Engine",
      Powerkwhp: "4.0kw / 5.5hp",
      CentrifugalForce: "25kn",
      CompactionDepth: "30cm",
      TravelSpeed: "6-16m/min",
      MovementType: "Reverse/Forward",
      CompactionPlateSize: "500 x 650 x 12 mm",
      RPM: "3600rpm",
      Weight: "170Kg",
    },
    {
      id: 3,
      Model: "RPC90",
      Drive_Type: "Diesel / Petrol Engine",
      Powerkwhp: "4.0kw / 5.5hp",
      CentrifugalForce: "15kn",
      CompactionDepth: "20cm",
      TravelSpeed: "20-23m/min",
      MovementType: "Forward (OneWay)",
      CompactionPlateSize: "480 x 520 x 10 mm",
      RPM: "3600rpm",
      Weight: "75Kg",
    },
    {
      id: 4,
      Model: "RPC3001",
      Drive_Type: "Diesel / Petrol Engine",
      Powerkwhp: "4.0kw / 5.5hp",
      CentrifugalForce: "25kn",
      CompactionDepth: "30cm",
      TravelSpeed: "6-16m/min",
      MovementType: "Forward",
      CompactionPlateSize: "320 x 1550 X 12 mm",
      RPM: "3600rpm",
      Weight: "130 kg",
    },
    {
      id: 5,
      Model: "RPC5001",
      Drive_Type: "Diesel / Petrol Engine",
      Powerkwhp: "4.0kw / 5.5hp",
      CentrifugalForce: "30kn",
      CompactionDepth: "30cm",
      TravelSpeed: "6-16m/min",
      MovementType: "Forward",
      CompactionPlateSize: "300 x 270 x 16 mm",
      RPM: "3600rpm",
      Weight: "170 kg",
    },
  ],
  "tamping rammer": [
    {
      id: 6,
      Model: "RTR80ES",
      Drive: "Electric Motor 1 Phase",
      Power: "3.0kw / 5.5hp",
      PlateSize: "310*330mm",
      BodyType: "Cast Iron",
      CentrifugalForce: "20kn",
      MovingSpeed: "0-25m/min",
      JumpingHeight: "40-75 mm",
      Voltage: "220 V 50-60Hz",
      MotorEngineRotation: "2800r/min",
      Dimensions: "600x600x1000mm",
      Weight: "90 Kgs",
    },
    {
      id: 7,
      Model: "RTR80E",
      Drive: "Electric Motor 3 Phase",
      Power: "3.0kw / 5.5hp",
      PlateSize: "310*330mm",
      BodyType: "Cast Iron",
      CentrifugalForce: "20kn",
      MovingSpeed: "0-25m/min",
      JumpingHeight: "40-75 mm",
      Voltage: "380V-415 V 50-60Hz",
      MotorEngineRotation: "2800r/min",
      Dimensions: "600x600x1000mm",
      Weight: "95 Kgs",
    },
    {
      id: 8,
      Model: "RTR100",
      Drive: "Honda Engine (Petrol)",
      Power: "4.0kw / 5.5hp",
      PlateSize: "310*330mm",
      BodyType: "Aluminium Body",
      CentrifugalForce: "25kn",
      MovingSpeed: "0-25m/min",
      JumpingHeight: "40-65 mm",
      Voltage: "NA",
      MotorEngineRotation: "3600r/min",
      Dimensions: "600x600x1000mm",
      Weight: "110 Kgs",
    },
    {
      id: 9,
      Model: "RTR90",
      Drive: "Robin Engine (Petrol)",
      Power: "4.0kw / 5.5hp",
      PlateSize: "310*330mm",
      BodyType: "Cast Iron",
      CentrifugalForce: "25kn",
      MovingSpeed: "0-25m/min",
      JumpingHeight: "40-65 mm",
      Voltage: "NA",
      MotorEngineRotation: "3600 Rpm/Min",
      Dimensions: "600x600x1000mm",
      Weight: "85 Kgs",
    },
    {
      id: 10,
      Model: "RTR110",
      Drive: "Changfa Engine (Diesel)",
      Power: "4.0kw / 5.5hp",
      PlateSize: "310*330mm",
      BodyType: "Aluminium Body",
      CentrifugalForce: "25kn",
      MovingSpeed: "0-25m/min",
      JumpingHeight: "40-65 mm",
      Voltage: "NA",
      MotorEngineRotation: "3600 Rpm/Min",
      Dimensions: "600x600x1000mm",
      Weight: "100 Kgs",
    },
  ],
  "vibratorry road roller": [
    {
      id: 1,
      Model: "RVR600S",
      ExcingForce: "15kn",
      EngineType: "Petrol/DieselEngine",
      StartingMode: "Manual/Automatic",
      Engine_Power: "5-7Hp",
      GradeabilityClimbingCapacity: "25%",
      VibrationFrequency: "70Hz",
      CompactionofSoilLinearLoad: "25cm",
      RollerSize: "Front600x425MM",
      DriveMode: "HydraulicStation",
      SpeedRange: "0-3km/h",
      VibrationControl: "AutoMagneticClutch",
      WalkingMode: "Forward/Backward",
      WalkingSpeed: "0-3km/h",
      WaterTankCapacity: "4Ltr",
      HydraulicTankCapacity: "15Ltr",
      Dimensions: "1000x1000x1200mm",
      Weight: "330kg",
    },
    {
      id: 2,
      Model: "RVR600G/H/C",
      ExcingForce: "20-25kn",
      EngineType: "Petrol/DieselEngine",
      StartingMode: "Manual/Automatic",
      Engine_Power: "08-13Hp",
      GradeabilityClimbingCapacity: "30%",
      VibrationFrequency: "70Hz",
      CompactionofSoilLinearLoad: "25cm",
      RollerSize: "Front600x425MM\nRear600x425MM",
      DriveMode: "HydraulicStation",
      SpeedRange: "0-3km/h",
      VibrationControl: "AutoMagneticClutch",
      WalkingMode: "Forward/Backward",
      WalkingSpeed: "0-5km/h",
      WaterTankCapacity: "20Ltr",
      HydraulicTankCapacity: "25Ltr",
      Dimensions: "1350x940x1220mm",
      Weight: "580kg",
    },
    {
      id: 3,
      Model: "RVR850",
      ExcingForce: "25-30kn",
      EngineType: "Petrol/DieselEngine",
      StartingMode: "Electric/Manual",
      Engine_Power: "10-15Hp",
      GradeabilityClimbingCapacity: "30%",
      VibrationFrequency: "70Hz",
      CompactionofSoilLinearLoad: "30cm",
      RollerSize: "Front 700x560 mm\nRear 500x426 mm",
      DriveMode: "Hydraulic Station",
      SpeedRange: "0-6Km/H",
      VibrationControl: "Electro Magnetic Clutch",
      WalkingMode: "Forward & Backward",
      WalkingSpeed: "0-5km/h",
      WaterTankCapacity: "20Ltr",
      HydraulicTankCapacity: "25Ltr",
      Dimensions: "1850x780x1050mm",
      Weight: "750Kgs",
    },
    {
      id: 4,
      Model: "RVR880",
      ExcingForce: "25kn",
      EngineType: "Petrol / Diesel Engines",
      StartingMode: "Electric/Manual",
      Engine_Power: "10-13Hp",
      GradeabilityClimbingCapacity: "30%",
      VibrationFrequency: "70Hz",
      CompactionofSoilLinearLoad: "30cm",
      RollerSize: "Front 740x560 mm\nRear 800x560 mm",
      DriveMode: "Hydraulic Station",
      SpeedRange: "0-4Km/H",
      VibrationControl: "Electro Magnetic Clutch",
      WalkingMode: "Forward & Backward",
      WalkingSpeed: "0-5km/h",
      WaterTankCapacity: "40Ltr",
      HydraulicTankCapacity: "25Ltr",
      Dimensions: "2000x900x1400mm",
      Weight: "1000Kg",
    },
    {
      id: 5,
      Model: "RVR1000",
      ExcingForce: "35kn",
      EngineType: "Petrol / Diesel Engines",
      StartingMode: "Electric/Manual",
      Engine_Power: "10-15Hp",
      GradeabilityClimbingCapacity: "30%",
      VibrationFrequency: "70Hz",
      CompactionofSoilLinearLoad: "30cm",
      RollerSize: "Front 1000x530 mm\nRear 1000x530 mm",
      DriveMode: "Hydraulic Station",
      SpeedRange: "0-5Km/H",
      VibrationControl: "Electro Magnetic Clutch",
      WalkingMode: "Forward & Backward",
      WalkingSpeed: "0-7km/h",
      WaterTankCapacity: "60Ltr",
      HydraulicTankCapacity: "30Ltr",
      Dimensions: "1100 x 1900 x 1600 mm",
      Weight: "2000kgs",
    },
  ],
  "laser screed": [
    {
      id: 1,
      Model: "RLS325",
      Walking_speed: "0-2.5 km/Hour",
      Whole_flat_width: "2500 mm",
      Paving_thickness: "30-300 mm",
      Engine_power: "5.5 hp",
      Power_supply_system: "4.0KW single cylinder four stroke Petrol Engine",
      Vibration_system_control_method: "Eccentric vibration motor. 3000HZ",
      Vibration_frequency: "50Hz",
      Travel_control: "Manual Walk Behind",
      Laser_system: "Leica / Topcon Laser System",
      Control_mode_of_laser_system:
        "Laser scanning + high-precision servo actuator",
      Control_effect_of_laser_system: "Plane / Slope",
      Electric_servo_system: "Ori servo drive motor system",
      Auger_motor: "NA",
      Laser_Radar_Power_source: "Large capacity Lithiyum ion battery",
      Ground_Flatness: "≤±2mm",
      The_Ground_elevation_error: "≤±7mm/100m",
      Max_working_Radius: "≤200m",
      Working_Efficiencyhour: "200m²/h-350m²/h",
      Tire_Type: "733 ATV(1.8-2.2 BAR)X2\nNarrow Tire (1.6-2.1 BAR)X2",
      Weight: "220 Kgs",
      Dimension: "L2748*W2900*H2044",
    },
    {
      id: 2,
      Model: "RLS400",
      Walking_speed: "0-2.5 km/Hour",
      Whole_flat_width: "2500 mm",
      Engine: "Kholer CH260",
      Paving_thickness: "30-300 mm",
      Engine_power: "18 Hp",
      Engine_Type: "Petrol, V-cylinder engine, air cooling",
      Type_of_Leveling: "Independent suspension、Center rotation",
      Paving_Way: "scraper blade paving",
      Vibration_system_control_method: "Vibrating Motor",
      Boom_Motor: "High torque hydraulic motor",
      Vibration_frequency: "50Hz",
      Travel_control: "Manual mechanical adjustment of hydraulic value",
      Laser_system: "Leica / Topcon Laser System",
      Control_mode_of_laser_system:
        "Laser scanning + high-precision servo actuator",
      Control_effect_of_laser_system: "plane, slope",
      Electric_servo_system: "Imported Italy dinamic hydraulic drive motor",
      Auger_motor: "High torque hydraulic motor",
      Walking_Type: "Forward / Backward Switch Control Step Less",
      Tire_Type: "4 Tires",
      Weight: "740 Kgs",
      Dimension: "L3155*W3175*H1910",
    },
    {
      id: 3,
      Model: "LS-500",
      Engine: "Yanmar",
      Engine_Power: "20kw@2200RPM",
      WalkingSpeed: "0-9km/Hour",
      VibrationFrequency: "3000RPM",
      AugerSpeed: "200RPM",
      ArmExtended: "5Mtr",
      Wiperlengt: "2.5Mtr",
      LevelingArea: "13m²",
      MaximumRotationAngle: "360Degree",
      LaserRadar: "Leica/Topcon",
      LaserReciever: "Sauer",
      GradeControlSystem: "2-wheelPowerSteering",
      SteeringControl: "Standard",
      SelfLevellingHeadControl: "Standard",
      SoftLandingHeadControl: "ManualValveLever",
      StabilizerControlVolume: "70Ltr",
      FuelTank: "70Ltr",
      HydraulicOilTank: "3.5Tons",
      Weight: "L4000xW2080xH1900",
    },
  ],
  "grinding polishing machine": [
    {
      id: 1,
      Model: "RLD330",
      PanDiameter: "330mm",
      Motor_PowerKW: "3.0kw",
      PanSpeedrmin: "0-1800Rpm",
      GrindingBitpcs: "3pcs",
      WorkEfciency: "2500-3500m2/8h",
      motor_Speedrmin: "1440Rpm",
      Dimensions: "1100x500x950",
      WeightKgs: "135Kgs",
    },
    {
      id: 2,
      Model: "RLD400",
      PanDiameter: "400mm",
      Motor_PowerKW: "4.0kw",
      PanSpeedrmin: "0-1800Rpm",
      GrindingBitpcs: "5pcs",
      WorkEfciency: "3200-3500m2/8h",
      motor_Speedrmin: "1440Rpm",
      Dimensions: "1280x400x950",
      WeightKgs: "150Kgs",
    },
  ],
  "milling / scarifying machine": [
    {
      id: 1,
      Model: "RMM150",
      Drive: "Motor / Engine",
      Power: "7.5 KW / 9-13HP",
      MaximumMillingWidthmm: "250 mm",
      MaximumMillingDepthmm: "5 mm",
      ShaftQuantity: "6 Roots",
      BladeQuantity: "108 Pcs",
      Efciencym2h: "46 - 70",
      Dimensions: "910 x 470 × 880mm",
      Weight: "150 Kgs",
    },
  ],
  "road marking machine": [
    {
      id: 1,
      Model: "RM15",
      Capacity: "100 KG",
      RoadMarkingType: "Thremoplastic Paint",
      AutomationGrade: "Automatic",
      HeatingSystem: "PETROLEUM GAS",
      CoatThickness: "1MM TO 2.5MM",
      TankCapacity: "100 Ltr",
      StripColor: "ANY COLOUR",
      ScribingSpeed: "1.5 KM/H",
      Length: "100-450 MM",
      HeatingTemprature: "180°C to 210°C",
      MarkingShoeSize: "150mm Standard",
      GlassBeadSize: "10cm/15cm/20cm/30cm/40cm/45cm",
      Dimensions: "1320×820×1000mm",
      Weight: "135 KGS",
    },
  ],
  "suspended platform": [
    {
      id: 1,
      Model: "RLP800",
      PlatformSizes: "2.5 Meter x 2nos 1.5 Meter x 1nos 1Meter x 1no.s",
      MaterialofPlatform: "M.S. Steel Platform & Beta Dip Hot Galvanized",
      BalanceWeight: "1000 Kgs",
      Ratedload: "800 Kgs",
      AscendSpeed: "9-11m/min",
      Wirerope: "4x31 Sw-FC-9.1",
      WireropeSize: "9.1mm",
      WireropeLength: "75/100/150 meters",
      StructureWeightApprox: "900-950 kg",
      CounterWeight: "1000kg",
      RatedLiftingforce: "8 Kn",
      Power: "1.8kw x 2 no.s",
      Voltage: "AC 380V/415V 3 phase",
      Motor_Power: "2.0 Kw",
      Breaking: "15 NM",
      Safetylock: "Tilt proof safety lock (2 no.s)",
      SuspensionMechanism: "Hot Galvanised Steel",
      HeightAdjusting: "1.15m-1.75m",
      FrontBeamextension: "1.1m-1.7m",
      CableLine: "3*2.0+2*1 YC-5",
      ControlPannel: "1 Set Operating Type",
    },
    {
      id: 2,
      Model: "RHT500",
      LiftingHeight: "30 Mtr",
      Drive: "Motor Type Electric Winch With Gearbox Motor",
      Capacity: "300-500 Kgs",
      WireRopeSize: "6mm dia (6x36) galvanized",
      Motor_Power: "1.85 kW / 1 Ph Copper Winding",
      Boom: "Adjustable Boom",
      BoomLength: "5 to 6 ft",
      Swivel: "360 degree rotation",
      BreakType: "Clutch Type Break",
    },
  ],
  "stand tyre mixer": [
    {
      id: 1,
      Model: "MIX180S",
      Capacity: "180 LTR",
      Motor_Type: "Diesel Engine",
      Voltage: "220-240V 50hz 1 Phase",
      MotorEngine_Power: "1.8kw",
      Weight: "60 Kgs",
      motor_Speed: "2800 RPM",
      MixingTankSpeed: "28 RPM",
    },
    {
      id: 2,
      Model: "MIX220S",
      Capacity: "220 LTR",
      Motor_Type: "Diesel Engine",
      Voltage: "220-240V 50hz 1 Phase",
      MotorEngine_Power: "2.2 kw",
      Weight: "75 Kgs",
      motor_Speed: "2800 RPM",
      MixingTankSpeed: "28 RPM",
    },
    {
      id: 3,
      Model: "MIX260S",
      Capacity: "260 LTR",
      Motor_Type: "Diesel Engine",
      Voltage: "220-240V 50hz 1 Phase",
      MotorEngine_Power: "2.4 kw",
      Weight: "95 Kgs",
      motor_Speed: "2800 RPM",
      MixingTankSpeed: "28 RPM",
    },
    {
      id: 4,
      Model: "MIX5001",
      Capacity: "450 LTR",
      Motor_Type: "Diesel Engine",
      Voltage: "220-240V 50hz 1 Phase",
      MotorEngine_Power: "5HP/3.75 kw",
      Weight: "850 Kgs",
      motor_Speed: "3000 RPM",
      MixingTankSpeed: "18RPM",
    },
  ],
  "trolley mixer": [
    {
      id: 1,
      Model: "MIX180T",
      Capacity: "180 LTR",
      MotorEngine_Power: "MOTOR/ENGINE TYPE",
      Voltage: "220-240V 50hz 1 Phase",
      MotorEngine_Power: "1.8kw",
      Weight: "65 Kgs",
      motor_Speed: "2800 RPM",
      Mixingtankspeed: "28 RPM",
    },
    {
      id: 2,
      Model: "MIX230T",
      Capacity: "230 LTR",
      MotorEngine_Power: "MOTOR/ENGINE TYPE",
      Voltage: "220-240V 50hz 1 Phase",
      MotorEngine_Power: "2.0 kw",
      Weight: "70 Kgs",
      motor_Speed: "2800 RPM",
      Mixingtankspeed: "28 RPM",
    },
    {
      id: 3,
      Model: "MIX280T",
      Capacity: "280 LTR",
      MotorEngine_Power: "MOTOR/ENGINE TYPE",
      Voltage: "220-240V 50hz 1 Phase",
      MotorEngine_Power: "2.4 kw",
      Weight: "75 Kgs",
      motor_Speed: "2800 RPM",
      Mixingtankspeed: "28 RPM",
    },
    {
      id: 4,
      Model: "MIX350T",
      Capacity: "350 LTR",
      MotorEngine_Power: "MOTOR/ENGINE TYPE",
      Voltage: "220-240V 50hz 1 Phase",
      MotorEngine_Power: "2.6kw",
      Weight: "98 Kgs",
      motor_Speed: "2800 RPM",
      Mixingtankspeed: "28 RPM",
    },
  ],
  "shotcrete pump": [
    {
      id: 1,
      Model: "RSC15",
      Motor_Power: "15KW",
      voltageThreePhase: "380V-415V",
      walkingMotorWatt: "750W",
      theoreticalDisplacement: "6-08m3/h",
      maximumVerticalDeliveryDistance: "15m",
      maximumHorizontalDeliveryDistance: "40m",
      maximumTheoreticalWorkingPressure: "18Mpa",
      conveyingStoneSize: "0.5-2cm",
      pipeType: "Metal/Soft PVC",
      remoteType: "IR Remote",
      weight: "600kg",
      dimensions: "1900×700×1200mm",
      cylinderDiameterAndStroke: "120-360mm",
      aggregateDiameter: "5-20mm",
    },
  ],
  "concrete spraying machine": [
    {
      id: 1,
      Model: "RPL300",
      deliveryPressure: "3-6Mpa",
      voltage: "380V/415V/220v",
      Motor_Power: "7.5kw",
      horizontalConveyingHeight: "20m",
      verticalConveyingHeight: "15m",
      diameterOfPassingParticle: "3-4mm",
      displacementVolume: "120 Sqmt per hour",
      waterCementSandRatio: "0.7~1:1:3",
      bucketCapacity: "40L",
      weight: "180kg",
      supportingAirCompressor: "0.26",
      nozzleDiameter: "32mm",
      mainMotor_Power: "4000w",
      airCompressorPower: "2200w",
      size: "1600*500*1200",
    },
  ],
  "flooring equipment": [
    {
      id: 30,
      name: "Floor Scraper",
      price: 1800,
      description: "A machine for removing old flooring materials.",
    },
  ],
  engines: [
    {
      id: 31,
      name: "Diesel Engine",
      price: 1500,
      description: "A high-performance diesel engine.",
    },
  ],
  machines: [
    {
      id: 32,
      name: "Multi-Purpose Machine",
      price: 5000,
      description: "A versatile machine for various construction tasks.",
    },
  ],
};
